# Generated by Django 3.1.7 on 2021-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210406_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_deactivation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
